import { Metadata } from "next";
import LegalContact from "@/components/LegalContact";
import Link from "next/link";
import LegalSection from "@/components/LegalSection";

export const metadata: Metadata = {
  title: "Disclaimer | Kruti.io",
  description:
    "Important disclaimers regarding AI-generated content, LinkedIn integration, and use of Kruti.io.",
};

export default function DisclaimerPage() {
  return (
    <article>
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">
          Disclaimer
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Last Updated: March 10, 2026 &middot; Effective Date: March 10, 2026
        </p>
      </div>

      <LegalSection id="general" title="1. General Disclaimer">
        <p>
          <strong>Kruti.io</strong>, operated by <strong>Cinute InfoMedia</strong>, is
          provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without any warranties
          of any kind, whether express, implied, or statutory.
        </p>
        <p>
          To the fullest extent permitted by applicable law, Cinute InfoMedia disclaims
          all warranties, including but not limited to implied warranties of merchantability,
          fitness for a particular purpose, non-infringement, and accuracy of informational
          content.
        </p>
        <p>
          Your use of the Service is at your sole risk. We do not guarantee that the Service
          will be uninterrupted, error-free, or free from security vulnerabilities.
        </p>
      </LegalSection>

      <LegalSection id="ai-content-accuracy" title="2. AI-Generated Content Accuracy">
        <p>
          Kruti.io uses <strong>Google Gemini</strong> for both text and image generation &mdash; Gemini 2.5 Flash and Gemini 2.5 Pro for text, and Gemini 3.1 Flash Image for images. Regarding AI-generated content:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            AI models may produce content that is <strong>inaccurate, incomplete, misleading,
            or inappropriate</strong>. AI-generated text may contain factual errors, outdated
            information, or unintended biases.
          </li>
          <li>
            AI-generated images may not perfectly match prompts, may contain visual artifacts,
            or may not meet your creative expectations.
          </li>
          <li>
            The &ldquo;Human Mode&rdquo; feature attempts to match your writing style but does
            not guarantee that content will be indistinguishable from human-written text.
          </li>
          <li>
            <strong>You MUST review, verify, and edit all AI-generated content before
            publishing</strong> it to LinkedIn or any other platform. Publishing unreviewed
            AI content is done at your own risk.
          </li>
          <li>
            Kruti.io does not guarantee the originality of generated content. While AI models
            strive to produce unique outputs, there is a possibility of similarities with
            existing published content.
          </li>
          <li>
            Content strategies and recommendations generated by AI are suggestions only and
            may not be optimal for your specific industry, audience, or goals.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="linkedin-limitations" title="3. LinkedIn API and Integration Limitations">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Kruti.io relies on LinkedIn&rsquo;s OAuth API for authentication and the{" "}
            <code className="text-xs bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">w_member_social</code>{" "}
            scope for posting content. Our Service may be affected by LinkedIn API changes,
            rate limits, outages, or policy updates at any time.
          </li>
          <li>
            The auto-posting feature depends on LinkedIn API availability and your active
            authorization. LinkedIn may revoke API access or change API terms without notice.
          </li>
          <li>
            Kruti.io is <strong>not responsible</strong> for any LinkedIn account-related
            consequences including but not limited to: content removal, account restrictions,
            reduced reach (shadowbanning), or account suspension.
          </li>
          <li>
            LinkedIn&rsquo;s algorithm determines the visibility and reach of your posts.
            Kruti.io has no influence over LinkedIn&rsquo;s content distribution decisions.
          </li>
          <li>
            <strong>Kruti.io is not affiliated with, endorsed by, or sponsored by LinkedIn
            Corporation or Microsoft Corporation.</strong> LinkedIn is a trademark of LinkedIn
            Corporation.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="no-guarantee-results" title="4. No Guarantee of Results">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Kruti.io does <strong>not guarantee</strong> any specific outcomes, including but
            not limited to: likes, comments, shares, impressions, follower growth, lead
            generation, or business results.
          </li>
          <li>
            Feature descriptions such as &ldquo;5 AI-generated posts per week&rdquo; describe the
            platform&rsquo;s capacity, not guaranteed performance outcomes.
          </li>
          <li>
            Content performance depends on numerous factors outside our control, including
            LinkedIn&rsquo;s algorithm, your audience, industry trends, posting timing, and
            content relevance.
          </li>
          <li>
            Past performance, testimonials, or example metrics shown on our website are for
            illustrative purposes only and do not guarantee similar results for your account.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="professional-advice" title="5. Not Professional Advice">
        <p>
          Content generated by Kruti.io does <strong>not constitute</strong> professional,
          legal, financial, medical, career, or any other form of specialized advice.
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            Industry-specific content should be reviewed by qualified subject matter experts
            before publication.
          </li>
          <li>
            Content strategies and recommendations are AI-generated suggestions and should
            not be relied upon as professional consulting.
          </li>
          <li>
            For specific professional advice, please consult appropriately qualified
            professionals in the relevant field.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="third-party-services" title="6. Third-Party Services">
        <p>
          Kruti.io integrates with third-party services including LinkedIn, Google AI (Gemini
          ), and Razorpay. Regarding these integrations:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            We are not responsible for the availability, performance, accuracy, or security of
            third-party services.
          </li>
          <li>
            Third-party service outages, data breaches, policy changes, or discontinuation may
            affect Kruti.io&rsquo;s functionality.
          </li>
          <li>
            You should independently review the terms of service and privacy policies of all
            third-party services.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="payment-disclaimer" title="7. Payment and Subscription Disclaimer">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            All payments are processed by <strong>Razorpay Software Pvt. Ltd.</strong> Kruti.io
            is not a payment processor and does not handle sensitive financial data.
          </li>
          <li>
            Subscription charges are <strong>recurring monthly</strong> and will continue until
            you cancel. It is your responsibility to cancel before the renewal date if you do
            not wish to be charged.
          </li>
          <li>
            Please refer to our{" "}
            <Link href="/refund" className="text-[#0A66C2] dark:text-blue-400 hover:underline">
              Refund Policy
            </Link>{" "}
            for details on cancellations and refunds.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="limitation" title="8. Limitation of Liability">
        <p>
          To the maximum extent permitted by applicable law:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Cinute InfoMedia&rsquo;s total aggregate liability for any and all claims
            arising from or related to the Service shall not exceed the subscription fees you
            paid in the <strong>three (3) months</strong> immediately preceding the event giving
            rise to the claim.
          </li>
          <li>
            We shall not be liable for any loss of business, reputation, revenue, data,
            opportunities, or goodwill arising from the use of AI-generated content or the
            Service.
          </li>
          <li>
            We shall not be liable for any unauthorized posting or account activity resulting
            from the compromise of your LinkedIn account credentials.
          </li>
          <li>
            We shall not be liable for indirect, incidental, special, consequential, or punitive
            damages of any kind.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="indemnification" title="9. Indemnification">
        <p>
          You agree to indemnify, defend, and hold harmless <strong>Cinute InfoMedia Pvt.
          Ltd.</strong>, its officers, directors, employees, and agents from and against any and
          all claims, damages, losses, liabilities, costs, and expenses (including reasonable
          legal fees) arising from:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Content you publish using the Service (whether AI-generated or modified)</li>
          <li>Your violation of these terms or any applicable law</li>
          <li>Your use of the Service in a manner not authorized by these terms</li>
          <li>Any third-party claims related to content posted to your LinkedIn account via Kruti.io</li>
        </ul>
      </LegalSection>

      <LegalSection id="contact" title="10. Contact Us">
        <p>
          If you have questions about this Disclaimer, please contact us:
        </p>
        <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl p-4 mt-2 space-y-1.5">
          <LegalContact />
          <p>Website: kruti.io</p>
        </div>
      </LegalSection>
    </article>
  );
}
