import { prisma } from "@/lib/prisma";

// ── Lifetime Free Email Domains ──────────────────────────────────────────────
// Users with LinkedIn accounts from these email domains get a permanent free
// subscription. They are never charged and never see subscription/trial prompts.
const LIFETIME_FREE_DOMAINS = ["testriq.com", "cinutedigital.com"];

// ── Watermark ────────────────────────────────────────────────────────────────
// Appended to every post for trial users and lifetime-free-domain users.
// Paid subscribers and admins do NOT get the watermark.
export const WATERMARK_TEXT = "Post generated by Kruti.io\nhttps://kruti.io/";

/**
 * Check if an email qualifies for lifetime free subscription.
 * Matches @testriq.com and @cinutedigital.com domains (case-insensitive).
 */
export function isLifetimeFreeEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  const domain = email.toLowerCase().split("@")[1];
  return LIFETIME_FREE_DOMAINS.includes(domain);
}

/**
 * Determine if a user's posts should include the Kruti.io watermark.
 *
 * Watermark applies to:
 *   - Trial users (status = "trialing")
 *   - Lifetime free domain users (@testriq.com, @cinutedigital.com)
 *
 * NO watermark for:
 *   - Paid subscribers (status = "active" via Razorpay)
 *   - Admins (role = "admin")
 */
export function shouldShowWatermark({
  subscriptionStatus,
  email,
  role,
}: {
  subscriptionStatus: string | null | undefined;
  email: string | null | undefined;
  role: string | null | undefined;
}): boolean {
  // Admins never get watermark
  if (role === "admin") return false;

  // Lifetime free domain users always get watermark
  if (isLifetimeFreeEmail(email)) return true;

  // Trial users get watermark
  if (subscriptionStatus === "trialing") return true;

  // Paid subscribers (active, cancel_pending) do NOT get watermark
  return false;
}

/**
 * Ensure a qualifying user has an active lifetime subscription.
 * Creates or upgrades their subscription to active with a far-future expiry.
 * Returns true if a subscription was created/upgraded, false if already active.
 */
export async function ensureLifetimeSubscription(userId: string): Promise<boolean> {
  const existing = await prisma.subscription.findUnique({
    where: { userId },
  });

  // Already has an active lifetime subscription - nothing to do
  if (existing?.status === "active" && existing.currentPeriodEnd &&
      existing.currentPeriodEnd >= new Date("2090-01-01")) {
    return false;
  }

  // Create or upgrade to lifetime active subscription
  await prisma.subscription.upsert({
    where: { userId },
    create: {
      userId,
      status: "active",
      currency: "INR",
      currentPeriodEnd: new Date("2099-12-31T23:59:59Z"),
      trialEnd: null,
      trialRemindersSent: "",
      postsGeneratedThisCycle: 0,
    },
    update: {
      status: "active",
      currentPeriodEnd: new Date("2099-12-31T23:59:59Z"),
      trialEnd: null,
      trialRemindersSent: "",
    },
  });

  console.log(`[Lifetime] Granted lifetime free subscription to user ${userId}`);
  return true;
}

/**
 * Check if a user has an active subscription that allows content generation.
 * Returns allowed: false for expired trials, canceled, unpaid, or missing subscriptions.
 */
export async function checkActiveSubscription(userId: string): Promise<{
  allowed: boolean;
  reason?: string;
}> {
  // Super admins get lifetime access - bypass all subscription checks
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { role: true, email: true },
  });
  if (user?.role === "admin") {
    return { allowed: true };
  }

  // Lifetime free email domains - bypass all subscription checks
  if (isLifetimeFreeEmail(user?.email)) {
    // Ensure they have an active subscription record (auto-fix if somehow missing/expired)
    await ensureLifetimeSubscription(userId);
    return { allowed: true };
  }

  let sub = await prisma.subscription.findUnique({
    where: { userId },
  });

  if (!sub) {
    const trialEnd = new Date();
    trialEnd.setDate(trialEnd.getDate() + 7);
    try {
      sub = await prisma.subscription.create({
        data: {
          userId,
          status: "trialing",
          trialEnd,
          currency: "INR",
        },
      });
    } catch (err) {
      console.error("Failed to auto-create trial subscription in check:", err);
      return { allowed: false, reason: "No subscription found and failed to create one. Please try again or contact support." };
    }
  }

  if (sub.status === "active" || sub.status === "cancel_pending") {
    return { allowed: true };
  }

  if (sub.status === "trialing") {
    if (sub.trialEnd && sub.trialEnd < new Date()) {
      return {
        allowed: false,
        reason: "Your free trial has ended. Subscribe to continue creating content.",
      };
    }
    return { allowed: true };
  }

  return { allowed: false, reason: "Your subscription is not active. Please subscribe to continue." };
}

// ── Entitlement state ────────────────────────────────────────────────────────

export interface SubscriptionState {
  /** True when the user may use the app. */
  entitled: boolean;
  /** True when the dashboard should be locked behind the paywall. */
  locked: boolean;
  status: string;
  trialEnd: Date | null;
  /** Whole days left on the trial (ceil), or null when not trialing. */
  daysLeft: number | null;
  /** Trialing with under 24h left - the final-day nudge. */
  isLastDay: boolean;
}

/**
 * The single source of truth for "can this user use the app right now".
 *
 * The dashboard layout, the paywall and the API guards all read this, so the
 * rule lives in ONE place instead of being re-implemented per surface (which is
 * how admins ended up seeing "trial expired" banners).
 *
 * Mirrors checkActiveSubscription, including the admin and lifetime-domain
 * bypasses, and adds the trial countdown the UI needs.
 */
export async function getSubscriptionState(userId: string): Promise<SubscriptionState> {
  const base = {
    entitled: true,
    locked: false,
    status: "active",
    trialEnd: null as Date | null,
    daysLeft: null as number | null,
    isLastDay: false,
  };

  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { role: true, email: true },
  });

  // Admins and lifetime-free domains are never gated.
  if (user?.role === "admin") return base;
  if (isLifetimeFreeEmail(user?.email)) {
    await ensureLifetimeSubscription(userId);
    return base;
  }

  const sub = await prisma.subscription.findUnique({ where: { userId } });
  if (!sub) {
    // No record at all. This is an anomaly - the jwt callback creates a trial at
    // sign-in - so do NOT paywall them: checkActiveSubscription creates the trial
    // on the first real action. Locking here would strand a legitimate new user,
    // and this read path deliberately has no side effects.
    return { ...base, status: "none" };
  }

  // Paid, or cancelled but still inside the paid period.
  if (sub.status === "active" || sub.status === "cancel_pending") {
    return { ...base, status: sub.status, trialEnd: sub.trialEnd };
  }

  if (sub.status === "trialing") {
    const now = Date.now();
    const endMs = sub.trialEnd ? sub.trialEnd.getTime() : 0;
    const msLeft = endMs - now;
    if (msLeft > 0) {
      return {
        entitled: true,
        locked: false,
        status: "trialing",
        trialEnd: sub.trialEnd,
        daysLeft: Math.ceil(msLeft / 86400000),
        // Final-day nudge fires inside the last 24 hours.
        isLastDay: msLeft <= 86400000,
      };
    }
    // Trial ran out.
    return {
      entitled: false,
      locked: true,
      status: "trialing",
      trialEnd: sub.trialEnd,
      daysLeft: 0,
      isLastDay: false,
    };
  }

  // canceled | past_due | unpaid | anything unknown - not entitled.
  return {
    ...base,
    entitled: false,
    locked: true,
    status: sub.status,
    trialEnd: sub.trialEnd,
  };
}
